### ISSUE TITLE
Query Builder editor not displaying SPARQL query correctly

### ISSUE THREAD

**Issue by judie90** [LinDA-tools/LindaWorkbench#135]

**Comment by smouzakitis** [comment]
It seems there is a problem with some specific Chrome plugin. Keeping the image for future reference
![screen shot 2015-01-26 at 12 16 03](https://cloud.githubusercontent.com/assets/1720797/5900192/2040200c-a56f-11e4-893a-524141e61cea.jpg)

**Comment by smouzakitis** [comment]
It works fine in all browsers (mac and windows). Maybe it was a problem with a specific chrome plugin. I keep the screenshot for future reference, if this issue appears. 
![screen shot 2015-01-26 at 12 16 03](https://cloud.githubusercontent.com/assets/1720797/5900219/727077be-a56f-11e4-99a2-724f355c08e0.jpg)
