### ISSUE TITLE
Difficult in mapping in Transformation tool

### ISSUE THREAD

**Issue by efotopoulou** [LinDA-tools/LindaWorkbench#148]
This issue will be better understood with an example

country,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
Belgium,125,123,121,119,117,115,115,117,120,120,120,119
Bulgaria,31,33,34,36,37,40,43,44,43,44,45,45
Czech Republic,74,77,79,80,81,84,82,83,81,83,82,82

in the above tabular data the years (2002,2003) can not get represented from the vocabulary mapping. If we place year instead the year value is not encapsulated correctly.

With the current version of transformation engine  in order to have a successful transformation the end user has to turn the data like this

country , year, value
Belgium,2002,125
Belgium,2003,123

This is very costly at time effort. The ideal would be to be able while transforming to have the option to create a nested rdfization or use the column as an extra property value.

Hope to discuss on this in berlin. :-)

**Comment by bbrand84** [comment]
I think on the Berlin meeting we came to the conclusion that we won't treat this special case. Am I right? 
(In any case the above mentioned case does not represent valid CSV and nevertheless would result in a lot of extra work.)

**Comment by smouzakitis** [comment]
yes you are right. we have another consumption application for this.
