### ISSUE TITLE
Forgot password UI error

### ISSUE THREAD

**Issue by bkapourani** [LinDA-tools/LindaWorkbench#151]
Please, have a look at the messed up UI, if sb forgets the password & want to change it.
Can we please check it and fix? Attached a screenshot for your convenience.  
Reproduction info:
1. System: Windows 2007
2. Browser: Mozilla Firefox 35.0.1
 
![forgot-password-ui-error](https://cloud.githubusercontent.com/assets/11331158/6527421/4eac25c6-c423-11e4-89b0-29a61af2ebd6.jpg)

Thank you,
Barbara.

**Comment by smouzakitis** [comment]
thanks Barbara we will have a look

**Comment by dipapaspyros** [comment]
Please verify that the problem is solved

**Comment by bkapourani** [comment]
It is working perfectly now!

Thank you!

On 6 March 2015 at 17:59, Dimitris Papaspyros <notifications@github.com>
wrote:

> Please verify that the problem is solved
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LinDA-tools/LindaWorkbench/issues/151#issuecomment-77582560>
> .
>



-- 
Barbara Kapourani
Information & Communication Systems Engineer

Them. Sofouli 49, 171 22 Nea Smyrni - Athens - Greece
Cell:    +30-697-5646878
Home: +30-210-9344943
emails: bkapurani@gmail.com, vkapourani@aegean.gr
