### ISSUE TITLE
R2R Mapping Designer - unable to upload a csv file

### ISSUE THREAD

**Issue by bkapourani** [LinDA-tools/LindaWorkbench#153]
![screenshot016](https://cloud.githubusercontent.com/assets/11331158/6708320/ca36ccd4-cd77-11e4-955b-a911a9ad4c9c.png)
![screenshot017](https://cloud.githubusercontent.com/assets/11331158/6708318/ca2a2ab0-cd77-11e4-8fe3-3cbd3f843b3c.png)
![screenshot015](https://cloud.githubusercontent.com/assets/11331158/6708319/ca2fb3fe-cd77-11e4-817a-b461bfc40f0d.png)

Please see the screenshots above. There are trials for uploading a csv file and converting it to RDF. Though that it was a "file name error" so I ve made some trials by renaming it. NO LUCK! Can you please help me on this?

Also, 2 other things I ve observed:
1. the red X icon near submit button should disappear in every new trial - now is not.
2. a note about the failure reason should inform the user, why this is happening.

**Comment by bbrand84** [comment]
works in the new transformation tool version
