### ISSUE TITLE
R2R Mapping Designer - Step 1 - "sign in" error and some other enhancements

### ISSUE THREAD

**Issue by bkapourani** [LinDA-tools/LindaWorkbench#155]
Please find attached a file with comments about R2R Mapping Designer:
1. One bug to be resolved, concerning the "sign in" label, and
2. Three other issues, as "nice to have or consider" - for UI improvement, if you all agree.
Thank you.
![transformation-step1-ui](https://cloud.githubusercontent.com/assets/11331158/6708579/509c73bc-cd7a-11e4-9707-0409ad24122e.png)

**Comment by lfarid** [comment]
thank you, @bkapourani. We will be fixing these bugs and integrating your ideas in the new design.

**Comment by bbrand84** [comment]
not relevant in the new transformation tool version
