### ISSUE TITLE
Transformation - unnecessary scrolling

### ISSUE THREAD

**Issue by bkapourani** [LinDA-tools/LindaWorkbench#157]
It seems that there is an unnecessary scrolling to the page. Can you please fix it?
Thank you.
![transformation-scrolling](https://cloud.githubusercontent.com/assets/11331158/6710985/ff25ee60-cd8c-11e4-8ddc-3f922148ec39.png)

**Comment by bbrand84** [comment]
not relevant in the new transformation tool version
