### ISSUE TITLE
Problem in uploading large file to datasources

### ISSUE THREAD

**Issue by efotopoulou** [LinDA-tools/LindaWorkbench#158]
when trying to upload a n3 datasource with size 1M i get the following message:

413 Request Entity Too Large
-------------------------------------
nginx/1.4.6 (Ubuntu)

**Comment by dipapaspyros** [comment]
Problem with nginx configuration solved -- set 15 MB of data limit to protect the Workbench that can be increased in production environments.
Please verify that it's solved.
