### ISSUE TITLE
X properties found

### ISSUE THREAD

**Issue by bkapourani** [LinDA-tools/LindaWorkbench#171]
X properties found: for the datasets that have up to 5 properties (e.g. area, period, value, metric, type)
it would be nice to have ALL the properties set/selected in the window, by default (so that, there is no need to add it each time, one-by-one) and an option “show all/none”, so that with ONE CLICK one can do the job.

**Comment by dipapaspyros** [comment]
I don't think this is good UX because the user should not expect instances to behave differently based on the number of properties they have.
