### ISSUE TITLE
Vocabulary Repository Suggest API does not expose vocabulary categories

### ISSUE THREAD

**Issue by dipapaspyros** [LinDA-tools/LindaWorkbench#179]
We intend to add the following functionality on the API. The inclusion itself is easy, as the categorization of vocabularies is implemented in the backend, but the vocabularies do not have any vocabulary information at the moment. As such categorization must be implemented manually, some time will be necessary.
If we agree on he how the category can be exposed by the API, you can continue working as if the vocabularies where categorized for the moment. My suggestion is the following:
- Add an optional parameter *category* that have one or more of the [predefined](https://github.com/LinDA-tools/LindaWorkbench/blob/master/linda/linda_app/lists.py#L355-L398) category codes: e.g ```...&category=AG``` or ```...&category=AG,ART,*```. Note ```*``` denoting any category.
- The priority of suggestions will be changed according to the order of categories, for example in the example ```...&category=AG,ART,*``` the result will contain suggestions from Agriculture domain, then the Arts, Recreation and Travel domain and then any other suggestion
- The number of results is already limited to 20 results for each page, unless pagination is explicitly disabled. A client can handle those results as it wishes, probably further limiting the number of suggestions if that's required.
If you agree with these additions to the API spec we can proceed developing according to the updated version.

**Comment by bbrand84** [comment]
I like the idea and think it will be sufficient. Although I think that the asterisk * in <code>...&category=AG,ART,*</code> is of no use.

**Comment by dipapaspyros** [comment]
The use of asterisk will be to allow client apps to prioritize specific categories without removing the other results from the response. So if i find nothing in the AG category i can fall back to generic suggestions.

**Comment by bbrand84** [comment]
okay, I was assuming an automatic fallback to generic suggestions. So would this mean that without that *, the result could possibly be empty? I assume that the categorization will never be perfect so that in the results, there should always be suggestion, whether the categorization fits or not. In my understanding the categorization parameter should just be an additional method to prioritize results in a better way.

**Comment by dipapaspyros** [comment]
I think it's more clear if we let clients decide whether or not they want results from all categories or *only* from those specifically stated. Without that *, the client has no such freedom. According to the quality of repository data it might actually be useful to eliminate unrelated categories

**Comment by dipapaspyros** [comment]
A simple scenario:

- http://linda.epu.ntua.gr:8000/coreapi/recommend/?property=width returns properties in the repository about ```width``` in general.
- http://linda.epu.ntua.gr:8000/coreapi/recommend/?property=width&category=IMA returns properties about ```width``` only defined in image-related vocabularies
- http://linda.epu.ntua.gr:8000/coreapi/recommend/?property=width&category=IMA,BIO returns properties about ```width``` defined in image or biology-related vocabularies

Note that the idea about ```*``` has been dropped for now. If ```category``` is specified, items **only** from vocabularies in the specified category/categories will be included in the result:
- A second, more generic query without categories can be used to fetch more generic results if required.
- The order of the categories is not taken under consideration when ordering results, as the ordering relies entirely on the Vocabulary Priority Mechanism we've already built in.

**Comment by dipapaspyros** [comment]
Also note the updated list of categories according to the vocabulary domains found [here](https://github.com/LinDA-tools/LindaWorkbench/blob/master/linda/linda_app/lists.py#L355-L395).
