### ISSUE TITLE
Unable to load and explore eurostat rdf datasets

### ISSUE THREAD

**Issue by efotopoulou** [LinDA-tools/LindaWorkbench#180]
unable to load and explore eurostat rdf datasets (http://eurostat.linked-statistics.org/data/) to linda workbench

Example 1)
For dataset env_air_emis.rdf

Error storing rdf data: MALFORMED DATA: XML document structures must start and end within the same entity. [line 1, column 1036]

Example 2)
For dataset env_air_gge.rdf it creates the datasource by can not explore it from query designer
Error while connecting to server

Thanks a lot!

**Comment by efotopoulou** [comment]
To this when finally i load an .n3 big datasource i get message
504 Gateway Time-out

**Comment by dipapaspyros** [comment]
LinDA Workbench does not parsing rdf/xml files greater than 10MB, n3/ntriples should be provided for large datasets. The correct message should be displayed indeed.
The 504 timeout is a security measure of the nginx configuration

**Comment by dipapaspyros** [comment]
This is not a problem of the Query Designer.

**Comment by dipapaspyros** [comment]
Fixed for datasets that can be uploaded in less than 10 minutes.
Idea: For larger datasets, upload them by providing a URL.
