### ISSUE TITLE
Interlinking between datasets

### ISSUE THREAD

**Issue by efotopoulou** [LinDA-tools/LindaWorkbench#181]
in case i want to interlink two datasets
A) dataset
<http://purl.org/linked-data/sdmx/2009/dimension#timePeriod> "1990-01-01"^^<http://www.w3.org/2001/XMLSchema#date>

B) dataset
http://purl.org/linked-data/sdmx/2009/dimension#refPeriod "1990"^^xsd:gYear;

How could i interlink them by year using the query designer???

**Comment by dipapaspyros** [comment]
Interlinking by values in the query designer is only possible if the values are equal.
A solution for our case would be to create again the dataset with ref periods with the "1990-01-01"^^http://www.w3.org/2001/XMLSchema#date format.

**Comment by dipapaspyros** [comment]
You can always elaborate in the SPARQL Query Editor
