### ISSUE TITLE
return common URL prefixes in API call

### ISSUE THREAD

**Issue by bbrand84** [LinDA-tools/LindaWorkbench#183]
What do you think about returning common prefixes along with the JSON result?
Like those:
<code>@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .</code>
<code>@prefix dc: <http://purl.org/dc/elements/1.1/> .</code>
<code>@prefix ex: <http://example.org/stuff/1.0/> .</code>

I think we will need them at some point.

**Comment by dipapaspyros** [comment]
You can ```GET http://linda.epu.ntua.gr:8000/api/vocabularies/versions/``` to fetch vocabularies and their prefixes.
