### ISSUE TITLE
Problem in exploring  datasource

### ISSUE THREAD

**Issue by efotopoulou** [LinDA-tools/LindaWorkbench#186]
For dataset youth_without_youth_triples (is already uploaded to http://linda.epu.ntua.gr)  i insert it but i can not explore is. LindaWorkbench give me error (Error while connecting to server) and from console i get the error  ValueError: invalid literal for int() with base 10: 'youth_without_youth_triples'

Same problem when trying to add to datasources analytic result  (for example
ValueError: invalid literal for int() with base 10: 'analyticsid10_version6_kmeans_resultdocum' )

As i can not attach an rdf file i pass it through mail.

**Comment by dipapaspyros** [comment]
The problem has been fixed (it was a mix in the URL resolution), please verify.
