### ISSUE TITLE
Union of query results. Detection of same columns

### ISSUE THREAD

**Issue by efotopoulou** [LinDA-tools/LindaWorkbench#189]
Minor issue. 
when i use the union pattern. the query designer does not detect the same column names. as a result i get a union with more columns that are empty depending on the datasource.

In order to fix it i have to change the names of the columns and give them a common name.

See as example the query #54 with description "bangkok_dangerous &amp; youth without youth text mining PPS"

Thanks a lot!

**Comment by efotopoulou** [comment]
an extra comment (using as example also query #54 )...when i put filters to description & text i order to do some mining in scenes with certain topics, i can only retrieve scenes from one datasource (movie), even though when querying them apart i know i could retrieve more rows.

**Comment by dipapaspyros** [comment]
Please verify that it's fixed

[Hint]: Clear your browser cache to make sure you've loaded the new versions of the scripts
