### ISSUE TITLE
not able to interlink World Factbook

### ISSUE THREAD

**Issue by efotopoulou** [LinDA-tools/LindaWorkbench#199]
not able to interlink World Factbook with ihme_gbd_2013_all_cause_mortality by Ref_Area property.

Getting Error: HTTP ERROR 404 Problem accessing /sparql/. Reason:  Not Found

when querying alone the World Factbook sparql endpoint it works perfectly.

Thanks a lot!

**Comment by dipapaspyros** [comment]
You should interlink this dataset's refArea with Eurostat, not World Factbook (the refArea urls are from Eurostat).
However I could not reproduce the error, just the query had no results.
