### ISSUE TITLE
Preference Window - click and activate

### ISSUE THREAD

**Issue by bkapourani** [LinDA-tools/LindaWorkbench#216]
The Preference (same applies for filter/options) window cannot be brought in front of the others (when clicked) - so its visibility is reduced. Can we fix this plz?

![screenshot002](https://cloud.githubusercontent.com/assets/11331158/11652145/b2fa8400-9d9e-11e5-8630-0c6a5b30d438.png)

**Comment by dipapaspyros** [comment]
Please verify this is fixed, you may need to clear your cache (on Chrome reload with ctrl+F5)

**Comment by bkapourani** [comment]
Great!Now it works!
Thank you!
