### ISSUE TITLE
Query designer bug with variable names for joins on intermediate class

### ISSUE THREAD

**Issue by jaw111** [LinDA-tools/LindaWorkbench#217]
I built the following query on the IMDB dataset in the demo query designer:

![image](https://cloud.githubusercontent.com/assets/2478333/17693069/6e1794a2-639d-11e6-8ada-5f3f472f1a56.png)

When inspecting the generated SPARQL you can see the variable name for the intermediate Performance class is named `?Actor_performance` when referred to from the `?Actor` and `?Film_performance` from the `?Film`.
As a result the query does not join the actor and film around the shared performance node and instead returns all actors matched to every film that has a performance.

```
PREFIX prf1: <http://data.linkedmdb.org/resource/movie/>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT DISTINCT ?Actor_actor_name ?Film_title
WHERE {
	?Actor a prf1:actor.
		?Actor prf1:actor_name ?Actor_actor_name.
		?Actor prf1:performance ?Actor_performance.
	?Film_performance a prf1:performance.
	?Film a prf1:film.
		?Film prf1:performance ?Film_performance.
		?Film dcterms:title ?Film_title.
}
```

The issue seems to be with two inbound links to a certain entity class.

**Comment by dipapaspyros** [comment]
Hello jaw111,

Could you save the query in the designer and send me a link in order to investigate the issue?
Best,

Dimitris Papaspyros

**Comment by jaw111** [comment]
Here it is:

http://linda.epu.ntua.gr/query-designer/171/

**Comment by dipapaspyros** [comment]
Dear jaw111,

Thank you very much for finding this bug out. Your input is appreciated!
We're very sorry for the delayed response on this issue. Please verify that the correct query is now constructed.
Looking forward to hearing from you if you have any further questions or need any help about LinDA.
Best,

Dimitris Papaspyros
Decision Support Systems Laboratory, NTUA, Greece

**Comment by jaw111** [comment]
Yes, that has solved the issue, thanks!
